providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "python311Packages.virtualenv", "ffmpeg-full"]

[phases.install]
cmds = ["python3 -m venv /opt/venv", "source /opt/venv/bin/activate && pip install --upgrade pip", "source /opt/venv/bin/activate && pip install -r requirements.txt"]
